# Generated by Django 4.0.4 on 2022-05-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('data0', models.CharField(max_length=100)),
            ],
        ),
    ]
