# Generated by Django 4.0.4 on 2022-05-18 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0003_menber_delete_user_alter_post_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menber',
        ),
    ]
