# Generated by Django 4.0.4 on 2022-05-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='member',
            name='has_open_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='id_card',
            field=models.CharField(default='S000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='is_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='wrong_pwd_times',
            field=models.IntegerField(default=0),
        ),
    ]
