# Generated by Django 4.0.4 on 2022-05-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_member_date_of_birth_member_has_open_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mobile_number',
            field=models.CharField(default='0912345678', max_length=10),
        ),
    ]
