# Generated by Django 4.0.4 on 2022-05-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_member_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(default='19700101'),
        ),
    ]
