# Generated by Django 4.0.4 on 2022-05-19 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_member_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_card',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
