# Generated by Django 4.0.4 on 2022-05-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_member_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errortimes',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
