# Generated by Django 4.0.4 on 2022-05-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_errortimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cannot_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
    ]
